global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node_exporter
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: postgres_exporter
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: redis_exporter
    static_configs:
      - targets: ["redis_exporter:9121"]

  - job_name: etcd
    metrics_path: /metrics
    static_configs:
      - targets: ["etcd:2379"]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]

  - job_name: promtail
    metrics_path: /metrics
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: blackbox_exporter
    static_configs:
      - targets: ["blackbox_exporter:9115"]

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://grafana.sprite3366.com
          - https://wedding.sprite3366.com
          - https://sprite3366.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox_exporter:9115
